Apparently BigInteger.TWO was private in earlier Java.
Build failed in Jenkins, so switching to use valueOf.

> Task :compileJava
/var/lib/jenkins/workspace/demo/src/main/java/com/coveros/training/FibonacciIterative.java:26: error: TWO has private access in BigInteger
            if (!i.mod(BigInteger.TWO).equals(BigInteger.ZERO)) {
                                 ^
/var/lib/jenkins/workspace/demo/src/main/java/com/coveros/training/FibonacciIterative.java:39: error: TWO has private access in BigInteger
            i = i.divide(BigInteger.TWO);
                                   ^
2 errors

> Task :compileJava FAILED