Adjusting test to reflect how entropy framework handles time.
Succinctly, I adjusted the tests so they are no longer so precisely specific about how long it will take to brute force a password.  It's because as time goes on, processors will become more powerful and therefore each time you run the test, in theory it should take less time to brute force a password.  Therefore, the answer is always varying, and therefore I won't include it as a constant value.

Alright, this was interesting.

The tests had been working fine for the past year.  Then suddenly August 1, 2019 hit and they stop working.  WHAT!??!

Well I contacted the author of the framework and he explained it to me.  In order to keep up with ever-improving processor speeds, he had code in the system to automatically up the speed of processors a year after the last revision date of the framework, which was August 1, 2018.

He replied that there is code in the ConfigurationBuilder class which handles this - specifically getMooresMultiplier() and getDefaultGuessTypes().

I suggested to change the code so that these multipliers are always being updated, rather than once a year which is rare and surprising.

Email chain:

Byron Katz <byron.katz@coveros.com>
10:10 AM (3 hours ago)
to adambrusselback

Adam,

How are you?

I noticed something interesting with Nbvcxz a few days ago.  I've been using it the past year on a demo application,  https://github.com/7ep/demo , and it works great.  I use BDD techniques in my testing, and some of my tests look like this:

# The following is a scenario that is extra documentation for the team.
# It helps  make concrete the reasons why the system requires more difficult passwords.
 @registration
 Scenario Outline: A user might try different passwords, but we are making sure they are excellent before we allow it.
     Given a user is in the midst of registering for an account
     When they try registering with the password <password>
     Then the system returns that the password has insufficient entropy, taking this long to crack: <time_to_crack>
     Examples:
         | password                | time_to_crack |
         | typical_password_123    | 1 hours       |
         | aaaaaa                  | instant       |
         | password123             | instant       |
         | really_totally_long_wut | 564 centuries |

Interestingly, a few days ago this test began to fail with this message:

Testing started at 10:06 AM ...
C:/Users/byron/demo/src/bdd_test/resources/com/coveros/training/authentication.feature
2019-08-02 10:06:42,202 INFO minimum entropy for password was not met
org.junit.ComparisonFailure: expected:<[1 hour]s> but was:<[46 minute]s>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at com.coveros.training.RegistrationStepDefs.theSystemReturnsThatThePasswordHasInsufficientEntropyTakingThisLongToCrackTime_to_crack(RegistrationStepDefs.java:98)
at ✽.the system returns that the password has insufficient entropy, taking this long to crack: 1 hours(C:/Users/byron/demo/src/bdd_test/resources/com/coveros/training/authentication.feature:44)

2019-08-02 10:06:42,416 INFO minimum entropy for password was not met2019-08-02 10:06:42,584 INFO minimum entropy for password was not met2019-08-02 10:06:42,734 INFO password met required entropy
org.junit.ComparisonFailure: expected:<[564] centuries> but was:<[398] centuries>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at com.coveros.training.RegistrationStepDefs.theSystemReturnsThatThePasswordHasInsufficientEntropyTakingThisLongToCrackTime_to_crack(RegistrationStepDefs.java:98)
at ✽.the system returns that the password has insufficient entropy, taking this long to crack: 564 centuries(C:/Users/byron/demo/src/bdd_test/resources/com/coveros/training/authentication.feature:44)

I've started looking through the code, wondering why the calculation has changed.  I didn't even change the version of Nbvcxz I'm using - I'm still using version 1.4.3.  It's odd.  Any ideas?

If you want to try it yourself, the only dependency for my app is Java 8 or above.

Thanks,
--

Byron Katz

Senior Technical Consultant

Coveros Training

Byron Katz
11:13 AM (2 hours ago)
and to see the tests run (and fail), do gradlew cucumber

Adam Brusselback
11:29 AM (1 hour ago)
to me

Hey there Byron, I know exactly what happened with your situation...

It has to do with the code below (found in the ConfigurationBuilder class):

    /**
     * Returns the Moore's law multiplier we're using for getDefaultGuessTypes().
     *
     * We will only return a multiplier greater than 1 if it has been more than year since we've updated the constants.
     * The date for this function is: 2018-08-01
     *
     * @return the Moore's Law multiplier
     */
    public static BigDecimal getMooresMultiplier()
    {
        double years = (System.currentTimeMillis() - START) / YEAR;

        // Only use the multiplier if we haven't updated the value date in over a year.
        if(years <= 1d)
        {
            years = 0;
        }

        // the multiplier for Moore's law is 2 to the power of (years / 2)
        return BigDecimal.valueOf(Math.pow(2d, years / 2d));
    }

    /**
     * This list was compiled in August 2018 using a baseline of what could be bought for roughly $20k usd for the offline attack values.
     * <p>
     * In the case this library is no longer maintained (or you choose to stay on an old version of it), we will scale the existing values by Moore's law.
     *
     * @param crackingHardwareCost the hardware cost (USD) to scale the guesses per second
     * @return The default list of guess types and associated values of guesses per second.
     */
    public static Map<String, Long> getDefaultGuessTypes(Long crackingHardwareCost)
    {
        BigDecimal moores_multiplier = getMooresMultiplier();
        BigDecimal cost_multiplier = BigDecimal.valueOf(crackingHardwareCost).divide(BigDecimal.valueOf(20000), 5, RoundingMode.HALF_UP);
        Map<String, Long> guessTypes = new HashMap<>();
        guessTypes.put("OFFLINE_MD5", cost_multiplier.multiply(moores_multiplier.multiply(BigDecimal.valueOf(250375000000L))).longValue());
        guessTypes.put("OFFLINE_SHA1", cost_multiplier.multiply(moores_multiplier.multiply(BigDecimal.valueOf(85963750000L))).longValue());
        guessTypes.put("OFFLINE_SHA512", cost_multiplier.multiply(moores_multiplier.multiply(BigDecimal.valueOf(10780875000L))).longValue());
        guessTypes.put("OFFLINE_BCRYPT_5", cost_multiplier.multiply(moores_multiplier.multiply(BigDecimal.valueOf(130875L))).longValue());
        guessTypes.put("OFFLINE_BCRYPT_10", cost_multiplier.multiply(moores_multiplier.multiply(BigDecimal.valueOf(4129L))).longValue());
        guessTypes.put("OFFLINE_BCRYPT_12", cost_multiplier.multiply(moores_multiplier.multiply(BigDecimal.valueOf(1033L))).longValue());
        guessTypes.put("OFFLINE_BCRYPT_14", cost_multiplier.multiply(moores_multiplier.multiply(BigDecimal.valueOf(259L))).longValue());
        guessTypes.put("ONLINE_UNTHROTTLED", 100L);
        guessTypes.put("ONLINE_THROTTLED", 2L);
        return guessTypes;
    }

So this was put in place to make sure the guesses/second for the pre-configured guess types would scale even for people who were using old versions
of the library or if the library became un-maintained (has it already been a damn year since I last updated it... god time flies).

I really need to release an update which takes into account the release of the new generation of Nvidia and AMD GPUs which give much better
performance / dollar, since as you see above, the constant guesses/sec found in getDefaultGuessTypes are relative to what could be bought
for $20,000 usd by default (as of 2018-08-01 when I last updated the values).

So as far as making tests not fail... I need to think a little more about the best way to handle that.
By default, I would much rather the library auto-scale up guesses/sec so it reflects how in the real world. A password that may have been unable
to be cracked in 100 years with hardware available 15 years, it may be vulnerable to the hardware of today in days. External libraries may not be
kept up to date for a lot of applications, so the default behavior of auto-scaling is in my opinion very important.

Would love to hear what your thoughts are.

Byron Katz <byron.katz@coveros.com>
12:16 PM (1 hour ago)
to Adam

Adam,

Thanks so much for your quick answer, that makes a lot of sense.  I investigated the code, and came up with some initial thoughts:

I suppose one of the pressing concerns is quantum computing.  I don't know a lot about it, but it might be able to totally change the game for how many brute force attacks per second could be done.

That aside, I think the most robust approach is to include the calculation for autoscaling as part of the original function.  That is to say something like this:

how long to fully brute force a password?

Today: 1,000 attempts per second
two years later: 2,000 attempts per second
four years later: 4,000 attempts per second
... etc.

The estimate for time should account for improving processing (Moore's law has been slowing down.  Probably best to be conservative, but to explain your thinking up front for users of your framework).  Since the calculation switches from being a constant function:

f(x) = x

to being a power function:

f(x) = 1000 * 2^(x-1)

you'll see that the answer should probably be like, 50 years instead of 500 centuries.  That's just a number I pulled out of thin air mainly, but the power function gets into high values way faster than the constant function.

(the domain, x here, being a unit of every doubling of speed, about every 2.5 years now)

Related to testing this:
instead of updating each year, update by the second (!).  That way, people who write tests will be forced to account for ever-shifting values, which is easier to handle than being surprised on a rare day.

For now, as a workaround I'm going to change the test code to be much more conservative and less precisely specific.  Time to crack must be above 50 years, for example.